CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	delet INTEGER DEFAULT NULL,
	name TEXT UNIQUE,
	p TEXT,
	q TEXT,
	g TEXT,
	x TEXT,
	y TEXT
);

CREATE TABLE IF NOT EXISTS events(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	userid INTEGER SECONDARY KEY,
	time TEXT,
	wish TEXT,
	x FLOAT,
	y FLOAT,
	FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS users_name ON users(name);

CREATE TRIGGER IF NOT EXISTS users_delete_by
AFTER INSERT ON users
BEGIN
    UPDATE users SET delet = strftime("%s", "now") + 780 WHERE delet IS NULL;
END;
