version: '2.1'
services:
  fireworx-checker:
    build: .
    ports:
      - 1813:1813
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=fireworx-mongo
      - MONGO_PORT=1814
      - MONGO_USER=fireworx_checker
      - MONGO_PASSWORD=fireworx_checker
  fireworx-mongo:
    image: mongo
    command: mongod --port 1814
    volumes:
      - ./data:/data/db
    ports:
      - 1814:1814
    environment:
      MONGO_INITDB_ROOT_USERNAME: fireworx_checker
      MONGO_INITDB_ROOT_PASSWORD: fireworx_checker
