version: '2.1'
services:
  fireworx-checker:
    build: .
    ports:
      - 1813:1813
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=fireworx-mongo
      - MONGO_PORT=27017
      - MONGO_USER=fireworx_checker
      - MONGO_PASSWORD=fireworx_checker
  fireworx-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: fireworx_checker
      MONGO_INITDB_ROOT_PASSWORD: fireworx_checker
